In [1]:
import numpy as np
import random 

In [ ]:
A = np.array([[56.0, 0.0, 4.4, 68.0],
              [1.2, 104.0, 52.0, 8.0],
              [1.8, 135.0, 99.0, 0.9]])

print(A)
print(A.shape)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]
(3, 4)


In [ ]:
cal = A.sum(axis=0) # Soma as linhas (axis=0) e retorna o vetor linha referente
print(cal)

[ 59.  239.  155.4  76.9]


In [ ]:
# Broadcasting
percentage = A / cal.reshape(1,4)

In [ ]:
print(percentage)

[[0.94915254 0.         0.02831403 0.88426528]
 [0.02033898 0.43514644 0.33462033 0.10403121]
 [0.03050847 0.56485356 0.63706564 0.01170351]]


In [ ]:
'''
Broadcasting em Python é tomar uma matriz ou vetor e fazer operacoes entre ela e um vetor de tamanho diferente.
Exemplos:
1. [[1],
    [2],
    [3]] + 100
    =
    [[1],
    [2],
    [3]] 
    + 
    [[100],
    [100],
    [100]]

2. [[1, 2, 3],
    [4, 5, 6]] + [[100, 200, 300]]
    =
    [[1, 2, 3],
    [4, 5, 6]]
     + 
    [[100, 200, 300],
    [100, 200, 300]]

Python Numpy altera o shape (reshape) da matriz/vetor para calcular as operacoes elemento a elemento
'''

In [3]:
# Exemplo 1
a = np.random.randn(2, 3)
display(a)
print(a.shape)
b = np.random.randn(2, 1)
display(b)
print(b.shape)
c = a + b
display(c)
print(c.shape)

array([[ 1.83387467, -0.440045  ,  1.14585532],
       [-1.47802145,  0.52079415,  0.40006386]])

(2, 3)


array([[-1.60547774],
       [-0.26684599]])

(2, 1)


array([[ 0.22839693, -2.04552274, -0.45962242],
       [-1.74486743,  0.25394816,  0.13321788]])

(2, 3)


In [5]:
# Exemplo 2
try:
  a = np.random.randn(4, 3)
  display(a)
  print(a.shape)
  b = np.random.randn(3, 2)
  display(b)
  print(b.shape)
  c = a + b
  display(c)
  print(c.shape)
except ValueError:
  print("ValueError: operands could not be broadcast together with shapes")

array([[-0.65865402, -0.9899943 ,  0.62829524],
       [-1.21307503, -0.37913783,  0.1115257 ],
       [ 0.02179093, -0.43941369, -1.66564125],
       [-1.08795825, -2.27174406, -1.68616212]])

(4, 3)


array([[-1.74296158,  1.30373733],
       [ 0.22385504, -0.44386982],
       [-1.146106  , -0.8425251 ]])

(3, 2)
ValueError: operands could not be broadcast together with shapes
