In [1]:
import numpy as np

In [2]:
a = np.random.randn(5)

In [3]:
print(a)

[ 0.03766266 -0.48463134  0.24266871  0.88092393  0.851097  ]


In [4]:
print(a.shape)

(5,)


In [5]:
print(a.T)

[ 0.03766266 -0.48463134  0.24266871  0.88092393  0.851097  ]


In [6]:
print(np.dot(a, a.T))

1.795567186814845


In [8]:
# Vemos dos resultados acima que nosso elemento "a" nao se comporta como um vetor linha,
# que era o que esperavamos. Portanto, vamos evitar usar coisas desse tipo
# Vamos usar de fato a seguinte implementacao, que eh mais intuitiva e retorna o esperado

a = np.random.randn(5,1)

In [9]:
print(a)

[[ 1.41486245]
 [ 0.06791601]
 [ 0.64793774]
 [-0.0781366 ]
 [-0.66782345]]


In [10]:
print(a.T)

[[ 1.41486245  0.06791601  0.64793774 -0.0781366  -0.66782345]]


In [11]:
print(np.dot(a, a.T))

[[ 2.00183574  0.09609181  0.91674277 -0.11055254 -0.94487833]
 [ 0.09609181  0.00461258  0.04400535 -0.00530673 -0.0453559 ]
 [ 0.91674277  0.04400535  0.41982331 -0.05062765 -0.43270802]
 [-0.11055254 -0.00530673 -0.05062765  0.00610533  0.05218145]
 [-0.94487833 -0.0453559  -0.43270802  0.05218145  0.44598817]]


In [12]:
# Os resultados acima sao como esperavamos!

assert(a.shape == (5, 1))
# Mais sobre o comando "assert" em Python aqui: https://www.educative.io/edpresso/what-does-assert-mean-in-python?